### ISSUE TITLE
large number of errors loading files

### ISSUE THREAD

**Issue by jwende** [node-red/i18n-viewer#9]
I get a large number of errors runing node index.js (catalog before - with similar errors):
node 10.15.3

eg:
{ [Error: ENOENT: no such file or directory, stat 'C:\2_Git\i18n-viewer\catalogs\node-red\master\packages\node_modules\@node-red\nodes\locales\*']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   'C:\\2_Git\\i18n-viewer\\catalogs\\node-red\\master\\packages\\node_modules\\@node-red\\nodes\\locales\\*' }

**Comment by jwende** [comment]
looks like a windows cmd parsing error - works on linux

**Comment by dceejay** [comment]
probably needs another \ to escape the \ - so `c:\\...` etc, or change to `c:/...`
